server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=valle_reg_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: TuContraseña123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

  web:
    resources:
      static-locations: classpath:/static/, file:uploads/
